config/routes.rb
Rails.application.routes.draw do


  root "posts#index"
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :posts

  resources :likes, only: [:create, :destroy]
  get 'pages/media'
  get 'pages/tos'
  get 'posts/:id/download', to: 'posts#download', as: 'download_post'
end

app/models/post.rb
class Post < ApplicationRecord

  extend FriendlyId
  friendly_id :title, use: :slugged



  has_one_attached :image
  has_one_attached :video
  acts_as_punchable
  belongs_to :user

  has_many :likes

  validates :image, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "description", "id", "title", "updated_at", "user_id"]
  end
end

app/controllers/posts_controller.rb
require "mini_magick"

class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
 before_action :authenticate_user!, except: [:index, :show, :download]

  # GET /posts or /posts.json
  def index


    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true)
    @posts = Post.most_hit(nil)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post.punch(request)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  def download
    @post = Post.friendly.find(params[:id])
    if @post.video.attached?
    send_data @post.video.download, filename: @post.video.filename.to_s 
    else
      send_data @post.image.download, filename: @post.image.filename.to_s 
    end

  end
  #Ex:- :default =>''

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update

    if @post.user_id == current_user.id
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy

    if @post.user_id == current_user.id
      @post.likes.destroy_all
    @post.destroy


    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end

  end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :image, :video, :user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, class: "contents") do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation" class="px-3 py-2 mt-3 font-medium text-red-500 rounded-lg bg-red-50">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", rows: 5 %>
  </div>
  <div class="my-5">
    <%= form.label :video %>
    <%= form.file_field :video, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", accept: "video/*" %>
  </div>
  <div class="my-5">
    <%= form.label :image %>
    <%= form.file_field :image, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <%= form.hidden_field :user_id, value: current_user.id %>
    <p>  By continuing you agree to our 
    <%= link_to "Terms of Use", pages_tos_path, style:"color: blue;" %> </p>
  <div class="inline">
    <%= form.submit "Upload Video", class: "rounded-lg py-3 px-5 bg-blue-600 text-white mt-2 inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id(post) %>" class="youtube-layout relative">

  <% if post.image.attached? %>
<%= image_tag(post.image, quality: 10)%>
  <% end %>

  <% if action_name != "show" %>
    <%= link_to post, class: "overlay flex items-center justify-center opacity-0 transition-opacity duration-300" do %>
      <div class="overlay-content text-center">
        <h2 class="post-title text-2xl text-white leading-tight mb-2"><%= post.title %></h2>
        <p class="text-white post-details text-sm">
          <%#= post.user.email %>
          <br>
          <%= time_ago_in_words(post.created_at) %> ago
        </p>
      </div>
    <% end %>
  <% end %>
</div>

<style>
.youtube-layout {
  position: relative;
  width: 100%;
  height: 200px;
  box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;
  display: inline-block;
  overflow: hidden;
}

.thumbnail {
  display: block;
  max-width: 100%;
  max-height: 100%;
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.overlay {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  opacity: 0;
  transition: opacity 0.3s;
}

.youtube-layout:hover .overlay {
  opacity: 1;
}

.overlay::after {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-image: radial-gradient(ellipse at center, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, .35) 20%);
  pointer-events: none;
}

.post-title {

  color: white;
  position: absolute;
  z-index: 300;
  top: 16px;
  left: 16px;
}

.post-details {
  color: white;
    z-index: 300;
  position: absolute;
  bottom: 16px;
  left: 16px;
}

/* Responsive changes */
@media screen and (max-width: 768px) {
  .youtube-layout {
    width: 100%;
  }
}


</style>

app/views/posts/edit.html.erb
<div class="w-full mx-auto md:w-2/3">
<h1 class="">Editing post</h1>
  <%= render "form", post: @post %>
  <div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>


</div>


<br>

app/views/posts/index.html.erb
<div class="row container mx-auto mt-12">
<%= search_form_for @q do |f| %>

<h1 class="text-3xl font-bold mb-4">
  Stunning royalty-free images & videos
</h1>
<h2 class="text-lg text-gray-600">
Download high quality stock images, videos shared by our community.
</h2>
<div class="flex justify-center items-center p-6 space-x-6 bg-white rounded-xl shadow-lg hover:shadow-xl transform transition duration-500">
  <div class="flex bg-gray-100 p-4 w-full space-x-4 rounded-lg">
    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 opacity-30" fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
    </svg>
    <%= f.search_field :title_cont, class: "bg-gray-100 outline-none w-full", placeholder: "Search for all stock media on Crumble" %>
  </div>
  <div class="bg-red-600 py-3 px-5 text-white  rounded-lg hover:shadow-lg transition duration-3000 cursor-pointer">
    <span>Search</span>
  </div>
</div>

<br>
  <% end %>
  <div class="w-full">
  <% if notice.present? %>
    <p class="inline-block px-3 py-2 mb-5 font-medium text-green-500 rounded-lg bg-green-50" id="notice"><%= notice %></p>
  <% end %>
  <div class="flex items-center justify-between">
    <%#= link_to 'New post', new_post_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>
  <div id="posts" class="min-w-full grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
    <%= render @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="w-full mx-auto md:w-2/3">
  <%= render "form", post: @post %>
  <%#= link_to 'Back to posts', posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/posts/show.html.erb
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

<div class="grid lg:grid-cols-2 grid-cols-1 mt-4 px-4">
<div class="youtube-layout">
  <% if @post.video.attached? %>
    <div class="video-container">
      <video controls>
        <source src="<%= url_for(@post.video) %>" type="video/mp4">
        
        Your browser does not support the video tag.
        
      </video>
      
    </div>
            <h2 class="text-1xl post-details">        Uploaded <%= time_ago_in_words(@post.created_at) %> ago</h2>
  <% else %>

    <% if @post.image.attached? %>
      <%= image_tag(@post.image, class: "thumbnail") %>
    <% end %>
  <% end %>
</div>

  <div class="overlay xl:text-align:left;  ">
    <div class="overlay-content">
      <h2 class="text-5xl post-details"><%= @post.title %></h2>
      <h2 class="text-2xl post-details"><%= @post.hits %> views </h2>




      <p class="post-details">
       Posted by <%= @post.user.full_name %>

      </p>
    </div>
    <br>
  <% if @post.video.attached? || @post.image.attached? %>
    <%= link_to 'Download', download_post_path(@post), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    
  <% end %>
  <% if current_user %>
<% if current_user.likes?(@post) %>
  <% unlike_button = button_to image_tag("heart-icon.svg", style:"height: 20px;"), like_path(@post.likes.find_by(user_id: current_user)), method: :delete, class:"mt-2 rounded-lg py-3 px-5 mt-5 bg-gray-100 inline-block font-medium" %>
  <%= unlike_button %>
<% else %>
  <% like_button = button_to image_tag("heart.svg", style:"height: 20px;"), likes_path, params: { like: { post_id: @post.id } }, method: :post, class:"mt-2 rounded-lg py-3 px-5 mt-5 bg-gray-100 inline-block font-medium" %>
  <%= like_button %>
<% end %>
       <h2 class="text-1xl post-details"> Likes: <%= @post.likes.count %> </h2> 

 
    <%if @post.user_id == current_user.id %>

     
          <%= link_to image_tag("edit.svg", style:"height: 20px;"), edit_post_path(@post), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block " %>

        <%= button_to image_tag("delete.svg", style:"height: 20px;"), post_path(@post), method: :delete, class: " rounded-lg py-3 px-5 bg-gray-100 font-medium" %>

    <% end %>
  <% end %>

</div>
<style>

  .youtube-layout {


  width: 65%;
  margin: 0 auto;
  }

  .thumbnail {
   display: block;
   max-width: 100%;
   max-height: 100%;
   width: auto;
   height: auto;
   margin: 0 auto;
   object-fit: contain;
  }

  .post-details {
  padding: 10px;
  }

  .post-title {
  font-size: 24px;
  font-weight: bold;
  margin-bottom: 8px;
  }

  .post-details p {
  font-size: 14px;
  }      .video-container {
        position: relative;
        padding-bottom: 56.25%; /* 16:9 aspect ratio (change as needed) */
        padding-top: 30px;
        height: 0;
        overflow: hidden;
      }

      .video-container video {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
      }
</style>