config/routes.rb
Rails.application.routes.draw do


  root "posts#index"
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :posts

  resources :likes, only: [:create, :destroy]
  get 'pages/media'
  get 'pages/tos'
  get 'posts/:id/download', to: 'posts#download', as: 'download_post'
end

app/views/layouts/_footer.html.erb
<!-- component -->
<!-- Foooter -->
<footer class="" style="background-color: #282828;    box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;
  left: 0;
  bottom: 0; width: 100%;">
  <div class="max-w-screen-xl px-4 py-12 mx-auto space-y-8 overflow-hidden sm:px-6 lg:px-8"  >
    <nav class="flex flex-wrap justify-center -mx-5 -my-2">
      <div class="px-5 py-2">
        <a href="#" class="text-base leading-6 text-white hover:text-gray-200">
          About
        </a>
      </div>
      <div class="px-5 py-2">
        <a href="#" class="text-base leading-6 text-white hover:text-gray-200">
          Blog
        </a>
      </div>
      <%# if current_user %>
      <div class="px-5 py-2">
        <%#= link_to "Account details", edit_user_registration_path, class:"text-base leading-6 text-white hover:text-gray-200" %>
      </div>
      <%# end %>
    </nav>
    <p class="mt-8 text-base leading-6 text-center text-gray-400">
      © 2023 Clipsink All rights reserved.
    </p>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Poppins:wght@500&family=Roboto:wght@500&display=swap" rel="stylesheet">
<!-- component -->
<div class="place-items-center">
  <section class="relative mx-auto">
    <!-- navbar -->
    <nav class="flex items-center justify-between text-white" style="background-color: #282828; box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;">
      <div class="flex items-center w-full px-5 py-6 w-90 xl:px-12">
        <a class="text-3xl font-bold font-heading nav-title" href="/">
          <!-- <img class="h-9" src="logo.png" alt="logo"> -->
          Clipsink
        </a>
        <!-- Nav Links -->
        <ul class="hidden px-4 mx-auto space-x-12  md:flex font-heading">
          <li><a class="hover:text-gray-200" href="/">Home</a></li>
          <% if current_user %>


            <li><a class="hover:text-gray-200" href="#">  <%= link_to "My Media", pages_media_path %></a></li>

            <%= button_to("Log Out", destroy_user_session_path, method: :delete) %></li>
          <% else %>
            <li><a class="hover:text-gray-200" href="#">  <%= link_to "Sign up", new_user_registration_path %></a></li>
            <li><%= link_to "Login", new_user_session_path, class:"bg-white hover:bg-gray-100 text-gray-800 py-2 px-4 border border-gray-400 rounded shadow" %></a></li>
          </ul>
        <% end %>
        <!-- Header Icons -->
      </div>
      <!-- Responsive navbar -->
      <%#= render "layouts/search_bar"%>
    </nav>
  </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clipsink</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.tailwindcss.com"></script>
    <%= favicon_link_tag 'faucet.png' %>
  </head>
  <body>
  
    <%= render 'layouts/navbar' %>
    
    <% if alert.present? && !notice.present? %>
<div role="alert">
  <div class="bg-red-500 text-white font-bold  px-4 py-2">
    Error
  </div>
  <div class="border border-t-0 border-red-400 rounded-b bg-red-100 px-4 py-3 text-red-700">
    <p><%= alert %> </p>
  </div>
</div>
<% end %>

<% if notice.present? && !alert.present? %>

<div role="notice">
  <div class="bg-green-500 text-white font-bold  px-4 py-2">
    Success
  </div>
  <div class="border border-t-0 border-green-400 rounded-b bg-green-100 px-4 py-3 text-white-700">
    <p><%= alert %> </p>
  </div>
</div>
<% end %>

    <div class="content ">
      <%= yield %>
    </div>
    <!-- 100% privacy-first analytics -->
<script async defer src="https://scripts.simpleanalyticscdn.com/latest.js"></script>
<noscript><img src="https://queue.simpleanalyticscdn.com/noscript.gif" alt="" referrerpolicy="no-referrer-when-downgrade" /></noscript>
  </body>
</html>
<style>
  html,body {
    height: 100%;

  }

  .content {
    min-height: calc(100% - 300px); /* set the height of your footer here */
    box-sizing: border-box;

  }
</style>